class HelloWorldPlugin {
  apply(compiler) {
    compiler.hooks.emit.tapAsync('MyPlugin', (compilation, callback) => {
      // Explore each chunk (build output):
      compilation.chunks.forEach(chunk => {

        // Explore each asset filename generated by the chunk:
        chunk.files
          .filter(filename => /\.css$/.test(filename))
          .forEach(filename => {
          // Get the asset source for each file generated by the chunk:
            var source = compilation.assets[filename].source();
            console.log();
            console.log();
            console.log(filename, '--------------------');
            console.log(source);
          });
      });

      callback();
    });
  }
}

module.exports = HelloWorldPlugin;
